drop table if exists addresses_in_authors cascade ;
drop table if exists addresses_in_customers cascade ;
drop table if exists author cascade ;
drop table if exists authors_of_book cascade ;
drop table if exists book cascade ;
drop table if exists book_in_order cascade ;
drop table if exists books_in_library cascade ;
drop table if exists book_types cascade ;
drop table if exists borrowing cascade ;
drop table if exists branch cascade ;
drop table if exists buyable_book cascade ;
drop table if exists copy cascade ;
drop table if exists customer cascade ;
drop table if exists genres_of_book cascade ;
drop table if exists library cascade ;
drop table if exists libraryorder cascade ;
drop table if exists librarysubscription cascade ;
drop table if exists publisher cascade ;
drop table if exists review cascade ;
drop table if exists subscriptions_in_order cascade ;
drop sequence if exists author_seq;
drop sequence if exists book_seq;
drop sequence if exists borrowing_seq;
drop sequence if exists branch_seq;
drop sequence if exists buyable_book_seq;
drop sequence if exists copy_seq;
drop sequence if exists customer_seq;
drop sequence if exists library_seq;
drop sequence if exists libraryorder_seq;
drop sequence if exists librarysubscription_seq;
drop sequence if exists publisher_seq;
drop sequence if exists review_seq;

